#                                                                        #
# Settings                                                               #
#                                                                        #

TYPO3:
  TYPO3CR:
    contentTypes:
      'TYPO3.PhoenixDemoTypo3Org:Registration':
        superTypes: ['TYPO3.TYPO3:Plugin']
        label: 'Editor Registration Plugin'
      'TYPO3.PhoenixDemoTypo3Org:Youtube':
        superTypes: ['TYPO3.TYPO3:ContentObject']
        group: 'General'
        icon: 'Images/Icons/White/youtube_icon-16.png'
        label: 'Youtube'

        properties:
          video:
            label: string
            default: 'Enter video id here'
        properties:
          width:
            label: string
            default: 'Breite'
        properties:
          height:
            label: string
            default: 'Höhe'